//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2024 The kflashback Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlashbackPolicy) DeepCopyInto(out *FlashbackPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlashbackPolicy.
func (in *FlashbackPolicy) DeepCopy() *FlashbackPolicy {
	if in == nil {
		return nil
	}
	out := new(FlashbackPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlashbackPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlashbackPolicyList) DeepCopyInto(out *FlashbackPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlashbackPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlashbackPolicyList.
func (in *FlashbackPolicyList) DeepCopy() *FlashbackPolicyList {
	if in == nil {
		return nil
	}
	out := new(FlashbackPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FlashbackPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlashbackPolicySpec) DeepCopyInto(out *FlashbackPolicySpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]TrackedResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Retention = in.Retention
	in.Storage.DeepCopyInto(&out.Storage)
	in.FieldConfig.DeepCopyInto(&out.FieldConfig)
	in.Tracking.DeepCopyInto(&out.Tracking)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlashbackPolicySpec.
func (in *FlashbackPolicySpec) DeepCopy() *FlashbackPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FlashbackPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackedResource) DeepCopyInto(out *TrackedResource) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExcludeNames != nil {
		in, out := &in.ExcludeNames, &out.ExcludeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeNames != nil {
		in, out := &in.IncludeNames, &out.IncludeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackedResource.
func (in *TrackedResource) DeepCopy() *TrackedResource {
	if in == nil {
		return nil
	}
	out := new(TrackedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.CompressSnapshots != nil {
		in, out := &in.CompressSnapshots, &out.CompressSnapshots
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldConfig) DeepCopyInto(out *FieldConfig) {
	*out = *in
	if in.IgnoreFields != nil {
		in, out := &in.IgnoreFields, &out.IgnoreFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncludeFields != nil {
		in, out := &in.IncludeFields, &out.IncludeFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldConfig.
func (in *FieldConfig) DeepCopy() *FieldConfig {
	if in == nil {
		return nil
	}
	out := new(FieldConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingConfig) DeepCopyInto(out *TrackingConfig) {
	*out = *in
	if in.Creations != nil {
		in, out := &in.Creations, &out.Creations
		*out = new(bool)
		**out = **in
	}
	if in.Updates != nil {
		in, out := &in.Updates, &out.Updates
		*out = new(bool)
		**out = **in
	}
	if in.Deletions != nil {
		in, out := &in.Deletions, &out.Deletions
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingConfig.
func (in *TrackingConfig) DeepCopy() *TrackingConfig {
	if in == nil {
		return nil
	}
	out := new(TrackingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackConfig) DeepCopyInto(out *KFlashbackConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackConfig.
func (in *KFlashbackConfig) DeepCopy() *KFlashbackConfig {
	if in == nil {
		return nil
	}
	out := new(KFlashbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KFlashbackConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackConfigList) DeepCopyInto(out *KFlashbackConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KFlashbackConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackConfigList.
func (in *KFlashbackConfigList) DeepCopy() *KFlashbackConfigList {
	if in == nil {
		return nil
	}
	out := new(KFlashbackConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KFlashbackConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackConfigSpec) DeepCopyInto(out *KFlashbackConfigSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(KFlashbackAISpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackAISpec) DeepCopyInto(out *KFlashbackAISpec) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackAISpec.
func (in *KFlashbackAISpec) DeepCopy() *KFlashbackAISpec {
	if in == nil {
		return nil
	}
	out := new(KFlashbackAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackConfigSpec.
func (in *KFlashbackConfigSpec) DeepCopy() *KFlashbackConfigSpec {
	if in == nil {
		return nil
	}
	out := new(KFlashbackConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackConfigStatus) DeepCopyInto(out *KFlashbackConfigStatus) {
	*out = *in
	if in.LastApplied != nil {
		in, out := &in.LastApplied, &out.LastApplied
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackConfigStatus.
func (in *KFlashbackConfigStatus) DeepCopy() *KFlashbackConfigStatus {
	if in == nil {
		return nil
	}
	out := new(KFlashbackConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackStorageSpec) DeepCopyInto(out *KFlashbackStorageSpec) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackStorageSpec.
func (in *KFlashbackStorageSpec) DeepCopy() *KFlashbackStorageSpec {
	if in == nil {
		return nil
	}
	out := new(KFlashbackStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackServerSpec) DeepCopyInto(out *KFlashbackServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackServerSpec.
func (in *KFlashbackServerSpec) DeepCopy() *KFlashbackServerSpec {
	if in == nil {
		return nil
	}
	out := new(KFlashbackServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFlashbackControllerSpec) DeepCopyInto(out *KFlashbackControllerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFlashbackControllerSpec.
func (in *KFlashbackControllerSpec) DeepCopy() *KFlashbackControllerSpec {
	if in == nil {
		return nil
	}
	out := new(KFlashbackControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlashbackPolicyStatus) DeepCopyInto(out *FlashbackPolicyStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceSummaries != nil {
		in, out := &in.ResourceSummaries, &out.ResourceSummaries
		*out = make([]ResourceSummary, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlashbackPolicyStatus.
func (in *FlashbackPolicyStatus) DeepCopy() *FlashbackPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FlashbackPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSummary) DeepCopyInto(out *ResourceSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSummary.
func (in *ResourceSummary) DeepCopy() *ResourceSummary {
	if in == nil {
		return nil
	}
	out := new(ResourceSummary)
	in.DeepCopyInto(out)
	return out
}
